-- QUERY TO REPLICATE BCD TABLE FROM PTRAN
-- Emily O'Grady, January 2025

SELECT 
    DESCRIPTOR as MISSION_DESCRIPTOR,
    COLLECTOR_EVENT_ID as EVENT_COLLECTOR_EVENT_ID,
    COLLECTOR_STATION_NAME as EVENT_COLLECTOR_STN_NAME,
    HEADER_START_DEPTH as DIS_HEADER_START_DEPTH,
    HEADER_END_DEPTH as DIS_HEADER_END_DEPTH,
    HEADER_START_LAT as DIS_HEADER_SLAT,
    HEADER_START_LON as DIS_HEADER_SLON,
    HEADER_START as DIS_HEADER_SDATE,
    HEADER_START_TIME as DIS_HEADER_STIME,
    DATA_TYPE_SEQ as DIS_DETAIL_DATA_TYPE_SEQ,
    METHOD as DATA_TYPE_METHOD,
    DATA_VALUE as DIS_DETAIL_DATA_VALUE,
    DATA_QC_CODE as DIS_DETAIL_DATA_QC_CODE,
    DETECTION_LIMIT as DIS_dETAIL_DETECTION_LIMIT,
    COLLECTOR as DIS_DETAIL_COLLECTOR,
    COLLECTOR_SAMPLE_ID as DIS_DETAIL_COLLECTOR_SAMP_ID
    --DESCRIPTOR || "_" || COLLECTOR_EVENT_ID || "_" || COLLECTOR_SAMPLE_ID as DIS_SAMPLE_KEY_VALUE
FROM biochem.bcdiscrete_mv
WHERE AVERAGED_dATA = 'N'
AND NAME = 'BCD2022667'
UNION ALL
SELECT
    dd.DESCRIPTOR as MISSION_DESCRIPTOR,
    dd.COLLECTOR_EVENT_ID as EVENT_COLLECTOR_EVENT_ID,
    dd.COLLECTOR_STATION_NAME as EVENT_COLLECTOR_STN_NAME,
    dd.HEADER_START_DEPTH as DIS_HEADER_START_DEPTH,
    dd.HEADER_END_DEPTH as DIS_HEADER_END_DEPTH,
    dd.HEADER_START_LAT as DIS_HEADER_SLAT,
    dd.HEADER_START_LON as DIS_HEADER_SLON,
    dd.HEADER_START as DIS_HEADER_SDATE,
    dd.HEADER_START_TIME as DIS_HEADER_STIME,
    dd.DATA_TYPE_SEQ as DIS_DETAIL_DATA_TYPE_SEQ,
    dd.METHOD as DATA_TYPE_METHOD,
    br.DATA_VALUE as DIS_DETAIL_DATA_VALUE,
    br.DATA_QC_CODE as DIS_DETAIL_DATA_QC_CODE,
    br.DETECTION_LIMIT as DIS_dETAIL_DETECTION_LIMIT,
    dd.COLLECTOR as DIS_DETAIL_COLLECTOR,
    dd.COLLECTOR_SAMPLE_ID as DIS_DETAIL_COLLECTOR_SAMP_ID
    --DESCRIPTOR || _ || COLLECTOR_EVENT_ID || _ || COLLECTOR_SAMPLE_ID as DIS_SAMPLE_KEY_VALUE
FROM biochem.bcdiscrete_mv dd, biochem.bcdiscretereplicates br
WHERE dd.AVERAGED_DATA = 'Y'
AND dd.discrete_detail_seq = br.discrete_detail_seq
AND NAME = 'BCD2022667'
;